### ISSUE TITLE
Multiplayer links are broken

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#1011]
They navigate to local drafts in main.

What happens:

- tap link to `@petname/foo` 
- you're navigated to `/foo`

What should happen:

- tap link to `@petname/foo`
- you're navigated to `@petname/foo`

**Comment by bfollington** [comment]
I think this is a duplicate of https://github.com/subconsciousnetwork/subconscious/issues/1002

**Comment by gordonbrander** [comment]
Closing as duplicate of #1002
