### ISSUE TITLE
`autosave` polling action is never cancelled after editor is disposed

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#1065]
After opening and closing several editors and then navigating to root on all tabs I see (many) `autosave` actions being generated indefinitely.

```
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
Action: autosave
...100s more
```

```swift
/// `MemoEditorDetail.swift`
static func start(
        state: MemoEditorDetailModel,
        environment: AppEnvironment
    ) -> Update<MemoEditorDetailModel> {
        let pollFx = AppEnvironment.poll(every: Config.default.pollingInterval)
            .map({ _ in MemoEditorDetailAction.autosave })
            .eraseToAnyPublisher()
        return Update(state: state, fx: pollFx)
    }
```

This seems likely the culprit.

**Comment by gordonbrander** [comment]
@bfollington can you confirm the version of ObservableStore you see this happening on?


I fixed a similar issue in https://github.com/subconsciousnetwork/ObservableStore/pull/45

**Comment by bfollington** [comment]
@gordonbrander Confirmed that we're using 0.6.1 (the latest release) on main and I can still reproduce it on simulator.

Trying to identify the simplest reproduction steps, I can get this to happen by opening and closing the editor multiple times but changing the note's link or audience seems to trigger it more reliably.
