### ISSUE TITLE
TestFlight launch

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#193]
- [x] Draft email announcement
   - [x] Update screenshots in post with FAB
- [x] Create testers Google Group
- [x] Set "no warranty" EULA
- [x] Update icon artwork
- [x] Tag release
- [x] Archive build
- [x] Submit to Test Flight / App Store Connect

**Comment by OdynOOb** [comment]
Hi there,
I'm new, so I'm lost :)

Is there a Test Flight beta I can participate in ?

**Comment by gordonbrander** [comment]
Hi @OdynOOb the software is currently in early alpha state, and test flight invites at this stage are being kept to a small group, since the software is not yet considered stable enough for a broad rollout. However, you can still build the software in XCode yourself, if curious.

To be notified when a broader TestFlight Beta rolls out, sign up here https://forms.gle/H6v5J8DJ64NGxN4A6

**Comment by OdynOOb** [comment]
Tx I signed up.
PS: I'm used to alpha testing ...
