### ISSUE TITLE
As a user, I want links to transclude the linked content

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#328]
As a user, I want links to transclude the linked content, so I can treat links as embeds for the content.

Related:

- #214
- #324

**Comment by bfollington** [comment]
While we've got something working **fairly** well using TK2 and custom rendering, there is _another_ way I can think to approach rendering transcludes inspired by https://twitter.com/tylerangert/status/1638643087256743936?s=20 (and a rendering accident I had locally).

From our existing layout code, we know the exact on-screen rectangles to render transclude views into. We could add a layer over the top of the text area and place UIKit wrappers around SwiftUI views at the exact positions and dimensions to provide _interactive_ components etc. The main challenge here is that A. it's fiddley and hacky and B. it could interfere with event propagation to the underlying view...

But the upsides are full SwiftUI rendering support including animations etc.
