### ISSUE TITLE
Set up default Subconscious sphere (bootstrapping sphere)

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#364]
For basic multiplayer #330, we need the ability to find a sphere to follow.

For MVP, this could be as simple as a list of all users in a shared phonebook. Obviously that won't scale, but it's a place to start.

**Comment by bfollington** [comment]
Is this closed now that #448 is in place?

**Comment by gordonbrander** [comment]
In progress. Purchased a device to own and manage this sphere. Will arrive 2023-07-27.

**Comment by gordonbrander** [comment]
Phone acquired.

**Comment by gordonbrander** [comment]
Subconscious sphere created did:key:z6MkfUzJYTBW8Q7mwCvKbVjzBt5LvEPRbpZ3Ni7aZZZekMat
