### ISSUE TITLE
Adjust icon sizing in app icon

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#423]
Currently we use the same size as e.g. mobile safari. However, it's too visually large, and most icons sit within a smaller inner circle bound. We should do a survey of other icons that have circular/close-to-circular marks, and align with the rough bounds of those app icons.

**Comment by bfollington** [comment]
![image](https://user-images.githubusercontent.com/5009316/223946098-9f5ca1a9-d5f5-43f1-9e60-0a2fee2f0b00.png)

Some circle icon examples from my phone. Looks like most apps are quite consistent with apple's inner circle radius.

**Comment by gordonbrander** [comment]
Subconscious matches Safari/Spotify/Settings/etc. The distinction is that for most of these icons the circle acts as a platform for the real icon.

This leaves Subconscious icon feeling big and cramped to me as compared to others. I sense that a radius closer to GH would feel mor comfortable. 

IIRC Apple has some guidelines about this that we should dig up.
