### ISSUE TITLE
Detail editor does not respect system font size settings

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#435]
Increasing (or decreasing) the base font on iOS causes the in-app text to resize correctly in all components _except_ the TextView. We're hardcoding the font-size as an attribute which seems to prevent dynamic resize, even though we use specific font sizes elsewhere in SwiftUI and _those_ adapt just fine.

# Default
<img width="485" alt="image" src="https://user-images.githubusercontent.com/5009316/223879046-713a08c1-9587-4541-9d41-05b6548c8280.png">

## Large Text
<img width="468" alt="image" src="https://user-images.githubusercontent.com/5009316/223879020-471a6e2e-1ee4-4970-af48-2c2798f566c5.png">

**Comment by gordonbrander** [comment]
Related to #436
