### ISSUE TITLE
App becomes non-responsive during sync with invalid gateway

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#439]
This _may_ be a simulator only issue (I'm currently unable to test this on-device due to #376). 

# Reproduction

1. App setup (create a sphere)
2. Configure your gateway URL with Tailscale running 
3. Sync with gateway successfully (unsure if we need this step)
4. Quit app
5. Kill Tailscale (so gateway is unreachable)
6. Re-open app
7. Tap settings icon
8. Watch the app hang until the the request to the gateway times out (60 seconds for me)
9. Settings sheet finally opens, showing error

If you manually run sync again, close the sheet and try to re-open it the app will hang until the timeout error occurs again.

<img width="371" alt="Screenshot 2023-03-09 at 12 13 04 pm" src="https://user-images.githubusercontent.com/5009316/223898983-9a296af1-882b-4eb7-9e84-bbde4dd1d2d5.png">

# Expected Behaviour

Sync would run and fail in the background, letting me use the app in the meantime.

# Notes

My gateway URL is `http://bfollington.sphere.test.subconscious.cloud` and I suspect that 50% of the issue stems from the fact that pinging that URL (without Tailscale) takes 60 seconds to actually timeout. Using a localhost gateway like `http://127.0.0.1:4433` instantly times out instead of waiting.

Of course, the UI should still not be blocking during that waiting period.

Here's a video of the issue:

https://user-images.githubusercontent.com/5009316/223899842-e6b237cb-b563-40d8-ba85-6a8012ad480a.mov

**Comment by gordonbrander** [comment]
@cdata also reports:

> So, still working to get this going. One thing I'm noticing is that the entire UI locks up while any network requests are in flight, which means when they time out you can't do anything for the duration of the timeout (and this seems to persist across closing / opening the app). 

Things to investigate:

- Are Noosphere calls/network requests being property kicked off in non-UI threads?
- Does the simulator actually support multiple threads? If not then dispatching through GDC should be expected to block.

**Comment by gordonbrander** [comment]
Sync and read are being issued asynchronously on the global dispatch queue, so should not be blocking UI https://github.com/subconsciousnetwork/subconscious/blob/main/xcode/Subconscious/Shared/Services/DataService.swift#L87

**Comment by gordonbrander** [comment]
Did some print debugging and profiling to determine:

- `DataService.syncSphereWithGateway` is running off main thread (in a serial queue)
- `NoosphereService.sync` (and `Sphere.sync` which it calls) are running off main thread (in their own serial queue)

**Comment by gordonbrander** [comment]
The issue is not being caused by thread explosion. I forced all of our async work onto a single serial dispatch queue, and it did not resolve the issue.

**Comment by gordonbrander** [comment]
To investigate: could this be caused by our use of https://developer.apple.com/documentation/combine/fail/receive(on:options:) in ObservableStore?

My understanding is that this just "bumps" the message to the main thread, rather than moving the execution work to the main thread, or causing a block on the main thread somehow.

https://www.avanderlee.com/combine/runloop-main-vs-dispatchqueue-main/

**Comment by gordonbrander** [comment]
Replacing the body of `Sphere.sync` with `Thread.sleep(forTimeInterval: 5)` hangs the UI for 5s. However, the body is definitely not running on main thread. So it seems something about our use of GDC is not keeping the UI thread un-blocked.

**Comment by gordonbrander** [comment]
I wonder if the sheet is somehow making a synchronous call to NoosphereService? If so, it would be stuck in the serial queue behind the sync.

**Comment by gordonbrander** [comment]
There is another hang, that I believe may be caused by calling `findUniqueAddressFor` in `autosave`.
