### ISSUE TITLE
Investigate possible Subtext parser regression

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#447]
@gordonbrander has noted that after refactoring the Subtext parser to use Regex (in https://github.com/subconsciousnetwork/subconscious/pull/422) there may have been a performance regression, despite it on-paper being faster.

We should perform profiling and compare timings to the old implementation to pinpoint the issue (if any) and address bottlenecks.

**Comment by gordonbrander** [comment]
Confirmed in unit test. Non-regex approach is 97% faster than regex approach (0.013s vs 0.381s). Not sure _why_ regex is so slow here, but we can put up with the inconvenience of a hand-written recursive descent parser in exchange for the sizeable perf win.
