### ISSUE TITLE
Investigate using actors for thread-safe services

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#460]
Swift now has a thread-safe `Actor` type, which is like a class, but enforces safety against data-races between different threads and tasks.

Currently we use `DispatchQueue.sync` to enforce thread-safety for certain services. We could investigate using actors instead. They are more ergonomic, and integrated with Swift's async features.

https://www.swiftbysundell.com/articles/swift-actors/

**Comment by bfollington** [comment]
We've started using actors as of https://github.com/subconsciousnetwork/subconscious/pull/501
