### ISSUE TITLE
Services Architecture

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#462]
We are currently pretty unprincipled about the way services are structured, and communicate with each other. This issue tracks ways we could clean that relationship up.

## Requirements

- Services should be single-purpose
- Services depend upon other services sometimes.
- Services should be mockable.
- Services are stateful. They are a facade over some source of truth.

Swift UI app considerations:

- Services are generally long-lived, usually for the lifetime of the app.
- Services must be able to initialize without failing (no throw, no nil)
    - Since services are long-lived, it is not practical to cope with failures once only at startup.
    - However methods of services may fail in any way they choose.

## A: Services with delegates

Outline:

- Services are single-purpose classes, structs, or actors.
    - Since services will be shared to many places, perhaps require them to be actors to ensure thread safety.
- Dependencies on other services are handled through mutable delegate properties.
    - Delegates can be configured during initialization, or by assigning to property.
- Delegate properties are **always** protocols, never concrete types.
    - This allows for mocking.
    - Very minimal protocols could be defined that only contain the dependencies needed for that service.

Sketch:

```swift
class FooService {
    var count: Int = 0
    var bar: BarServiceProtocol
    var baz: BazServiceProtocol

    func count() -> Int {
        let barCount = bar.count()
        let bazCount = baz.count()
        return count + barCount + bazCount
    }
}
```

This is very slight riff on what we already do. The main difference is using protocols for dependencies to allow for mocking and replacement.

Decent blog post about roughly this approach https://www.cocoawithlove.com/blog/separated-services-layer.html#lets-try-to-add-tests-to-cwlfeedreader

## B: Services with encapsulated dependencies

A riff on **A**. This approach would hide (encapsulate) service dependencies, to enforce the single-purpose-ness of each service.

Outline:

- Services are single-purpose classes, structs, or actors.
    - Since services will be shared to many places, perhaps require them to be actors to ensure thread safety.
- Dependencies on other services are handled through initializer arguments which are assigned to `private` properties of the service.
- Dependencies are **always** protocols, never concrete types.
    - This allows for mocking.
    - Very minimal protocols could be defined that only contain the dependencies needed for that service.

Sketch, similar to above but showing dependency hiding, and actor-forward approach:

```swift
actor FooService {
    var count: Int = 0
    private var bar: BarServiceProtocol
    private var baz: BazServiceProtocol

    init(bar: BarServiceProtocol, baz: BazServiceProtocol) {
        self.bar = bar
        self.baz = baz
    }

    func count() async -> Int {
        let barCount = await bar.count()
        let bazCount = await baz.count()
        return count + barCount + bazCount
    }
}
```

## Other considerations

We may want to investigate actors, rather than classes, as the basis for thread-safe services. See #460.

**Comment by bfollington** [comment]
I like this a lot, I think it's wise to get ahead of the service-spaghetti problem 👍 

I _much_ prefer the protocol being defined by the consumer, as opposed to every `Service` having a corresponding `ServiceProtocol` exposing every method.

**Comment by gordonbrander** [comment]
I'm going to call this fixed by https://github.com/subconsciousnetwork/subconscious/pull/501
