### ISSUE TITLE
Sync/cache followed users' spheres in the background

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#469]
This will be used to populate cross-sphere backlinks, as well as improve the speed of navigation through content that belongs to.

Enables #323

**Comment by bfollington** [comment]
This would automatically happen as part of https://github.com/subconsciousnetwork/subconscious/issues/554, since Noosphere already caches data

**Comment by gordonbrander** [comment]
@bfollington is this different from https://github.com/subconsciousnetwork/subconscious/pull/627?

**Comment by bfollington** [comment]
Duplicate of https://github.com/subconsciousnetwork/subconscious/issues/554
