### ISSUE TITLE
Authorize another client to access your sphere

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/subconscious#495]
## Story

As a user, I want to authorize multiple apps to own my sphere, so I can edit my notes from multiple devices.

## Notes

In Noosphere, we use a UCAN-based authorization scheme to enable other clients (which is to say, any program that uses a distinctive key when accessing Noosphere) to share access to your sphere. When one client authorizes another client to access a sphere, the other client is able to sync with the first client's designated gateway and perform write operations on that sphere.

Once https://github.com/subconsciousnetwork/noosphere/issues/307 is implemented, we should promptly add this capability to the Subconscious client. This will enable a user with multiple devices to work on their notebook from any of them. It will also enable clients like `orb` to sync sphere content back and forth with any other client (such as the Subconscious app).

**Comment by gordonbrander** [comment]
Per chat with @cdata we could scan QR code to get DID (or grab from address book), then sync sphere to gateway.

**Comment by bfollington** [comment]
From team meeting 2023-07-11:

To introduce a basic solution we can use a (dev-facing) input field in the app settings to paste in the DID (of a sphere managed by orb) and authorize it to manage _our_ sphere. We already have FFI support for this but we'll need to write the Swift wrapping functions around it.

(Currently this is possible in reverse: creating a sphere in Subconscious (offline), authorizing it via orb and then doing gateway surgery to join it up.)

**Comment by cdata** [comment]
See https://github.com/subconsciousnetwork/noosphere/blob/30820f425cef90d48687a4e4fd09552a28a1936e/swift/Sources/SwiftNoosphere/Noosphere.swift#L135 for FFI to authorize another DID.
