### ISSUE TITLE
Display petname from AddressBook on User Profile

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#500]
Currently we **always** display the preferred petname of a user on their profile, but if you are following them and have chosen a petname that differs from their preferred option we should render that.

e.g. if my preferred petname is `ben` but you follow me as `my-ben` then when you visit my profile you should see `@my-ben` not `@ben`.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/5009316/231336302-2cb3f84e-7b6f-4cb4-8cac-891a0ef63124.png">

Additionally, we should use the petname _from_ the AddressBook when we present unfollow UI

**Comment by gordonbrander** [comment]
Petname must take precedence over nickname (name user prefers). This is the trick that petname system uses to avoid global name contention.

**Comment by bfollington** [comment]
#635 has made this issue irrelevant.
