### ISSUE TITLE
Remove `AppDefaults.nickname` and use `_profile_` instead

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#559]
We no longer need to store a nickname in `AppDefaults` since a user can save this in their profile.

During onboarding we should still collect the nickname but write it to the underlying `_profile_` memo instead, after sphere creation.

We should still keep `AppDefaults.ownerKeyName` going forward.

**Comment by gordonbrander** [comment]
Note AppDefaults.ownerKeyName got replaced by Config.noosphere.ownerKeyName
