### ISSUE TITLE
Support traversal in `SphereProtocol.resolve(slashlink: Slashlink)`

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#578]
Currently the `SphereProtocol.resolve(slashlink: Slashlink)` extension method does not traverse to a sphere before resolving the petname to a DID. This restricts petname resolution to spheres you immediately follow.

We might consider traversing where needed to allow for the resolution of more distant spheres.

- It may be worth anchoring this to specific user stories / features.
- Traversing has different latency characteristics vs resolving same-sphere. It may also be worth having a separate method for traversing if we want that.
    - We could also say "if you want another sphere, traverse to another sphere", and make the slow thing more verbose.

**Comment by bfollington** [comment]
Fixed in https://github.com/subconsciousnetwork/subconscious/pull/633
