### ISSUE TITLE
Rendering profile as JSON when linked from notes

### ISSUE THREAD

**Issue by jsantell** [subconsciousnetwork/subconscious#584]
Adding a link in a note to `_profile_` resolves to a note titled "Your profile" and in the editable textbox is `{"bio":"hello", "nickname":"j", "version":"0.0"}`

**Comment by jsantell** [comment]
This also has the side-effect of showing up when searching or creating a new note; a note entry with "Empty note" and the subtitle "Your profile".

**Comment by jsantell** [comment]
If your profile has not been modified and does not yet exist, opening `/_profile_` creates a new note with the content `_profile_`; modifying profile afterwards goes back into JSON viewer mode, but the phantom `_profile_` (non JSON) still exists in backlinks, possibly indexed

**Comment by bfollington** [comment]
We should detect navigation attempts to any `_profile_` slug in a single codepath to make sure this can't happen.

Additionally, we should protect against creating a note called `_profile_` via tapping a link _or_ manually titling a note.
