### ISSUE TITLE
Editing profile image can cause crash

### ISSUE THREAD

**Issue by jsantell** [subconsciousnetwork/subconscious#588]
We aggressively query for the image URL set in a profile on every change; typing in a link e.g. "http://foo.com/profile.png" makes `NSUrlRequest` for each change:

* `h`
* `ht`
* `htt`
* `http`
* `http:`

The first few are invalid URLs, but the `http:` request goes through and causes an unhandled error, causing the application to hang. We should also be cautious about sending intermediary HTTP requests without confirmation.

**Comment by bfollington** [comment]
Try tightening up the parsing/validation. We are just trusting the swift URL type atm.
