### ISSUE TITLE
Notes count is not accurate

### ISSUE THREAD

**Issue by jsantell** [subconsciousnetwork/subconscious#593]
Currently I have 4 notes. My notes show 4 notes, but the notification bubble displays 5. Creating two more notes does not update the value, still at 5. Restarting the application, my 4 original notes, and 2 new notes, are all displayed, with the count now being 7. Could possibly be counting the hidden `_profile_` entry?

**Comment by jsantell** [comment]
This appears after viewing your own profile as a note

**Comment by bfollington** [comment]
Need to exclude any "hidden" slugs from the query. Should be possible with an in-memory filter after the query. 

Doing it in-query would be better but could be tricky.

**Comment by bfollington** [comment]
During playtesting today I observed that creating a new sphere and then a new note and returning to the notes list shows the count as `0` but, after a pull-to-refresh, it changes to `2` (counting `_profile_` and the note I made).

So there are TWO issues here:
- counting hidden memos as notes
- not updating the rendered count when expected
