### ISSUE TITLE
Long press on @name to see a list of identifiers

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#609]
We have up to three names for a user:

1. our petname for them
2. their profile nickname
3. their relative address to us

By long pressing on a name we could list all the known identifiers for a user. Potentially including their pfp, or other identifier badges.

**Comment by gordonbrander** [comment]
Capturing petname design system requirements in #615

**Comment by bfollington** [comment]
Closing this since we have AKA blocks now.
