### ISSUE TITLE
Colorize @names based on type of identifier

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#611]
From https://github.com/subconsciousnetwork/subconscious/issues/609:

> We have up to three names for a user:
> 1. our petname for them
> 2. their profile nickname
> 3. their relative address to us

These could be colorized by case to help with visual parsing:

1. petname: purple (accent)
2. nickname: pink/blue
3. address: grey

**Comment by gordonbrander** [comment]
Capturing petname system design requirements in #615
