### ISSUE TITLE
Petname UX

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#615]
This umbrella issue documents user stories, design goals and principles for petname UX.

WIP. We may eventually move it to the wiki.

## Petname design

User stories:
- As a user, I want friendly recognizable names for people I know so I can reference them.
- As a user, I want to see that this is the same person I know, so I can recognize them.
- As a user, I want acquaintances to have familiar names, so I can recognize them at a distance, and get to know them.
- As a user, I want to know if multiple people in my neighborhood follow this person, so I have a sense of whether they are part of my trusted social circle.

Principles:
- Petnames are human-friendly handles
- ["If we show a user a did, we have failed"](https://spritelyproject.org/news/petname-systems.html)
- Petnames should work in a plain text editor
- Petname in markup and petname in UI should not diverge in meaningful ways

Observations:
- The closer someone is, the more trustworthy they are.
    - This has the effect of encouraging small densely-connected networks.
- Trust falls off exponentially with address depth, because real social networks are exponentially distributed (scale-free).
    - Therefore, most useful relationships will be one step out `@bob.alice`
    - This has the effect of encouraging hubs
- The first and last name are the most important. The first name is the account you are referencing. The last name is the root of trust.

Tensions:
- Deep petnames (more than n levels deep) are unfriendly. They don't satisfy the friendliness goals (memorable name, familiarity), since they are long, difficult to read, and must frequently be truncated. They don't satisfy the trust goals (I know this person), because trust falls off exponentially. They are only nominally better than DIDs.
    - Traditional petname systems often include the concept of "[edge names](https://spritely.institute/static/papers/petnames.html)", or names that are one step out (`@bob.alice` in our scheme).
    - Few seem to go deeper, although GNU Name system does.

### Petnames should truncate in the middle

When truncating `@eve.dave.carol.bob.alice`.

- **GOOD**: `@eve...alice`
- **BAD**: `@eve.dave...`

The first name is the nickname for the resource being referred to, the last name is the root of trust.

 We could consider truncating everything > 2 steps out.

```
@bob.alice
@carol...alice
```

Tracking here #680 

### Show either petname or proposed name (nickname)

Keep it simple. If petname, just show petname. Otherwise, just show proposed name with some kind of "scare quote" treatment to indicate it's not a real name until you follow. Proposed names could come from user's profile, or from the petname given by the user you followed to get here.

Scare quotes:

- iOS says `Maybe: Carol`
- Italics
- Quote marks

On profiles, we could combine proposed name, the petname path you took to get there, and even a bit of the DID.

```
Maybe: Carol
AKA @caroline.bob.alice
#abc123
```

### Beyond N levels of depth, we could show nickname rather than petname

As a user, you want parasocial relationships to have stable recognizable names.

Additionally, deep petnames don't really fulfill the design goals of petnames (see petname design). When recursing deeply, you quickly end up with many confusing synonyms. Trust falls off exponentially with address depth, because real social networks are exponentially distributed (scale-free), anyway.

Instead, we could consider displaying nicknames (preferred names) for accounts you don't know, perhaps disambiguated with hashes.

```
@nick#1234 -- follow --> @nick
@(nick) -- follow --> @nick
```

Pros:
- Creates a stable name for parasocial accounts that you don't know, but see mutuals following. 

Cons:
- Mutuals already have a petname for the account, and so what you'll see in their posts will differ.
- May break the security model? 

### AKA

```
@theirpetname AKA @yourpetname
```

Discord does this to disambiguate Petnames.

### Bold and/or colors

If we relativize petnames in another user's follows, we could use bold styling or colors to indicate when their `@bob` is your `@bob`. For example,

- All of your petnames could be **bold**, while all edge names are not.
- All petnames could be one color, all edge names another

## Petname resources

- Petnames cheat Zooko's Triangle https://subconscious.substack.com/p/cheating-zookos-triangle
- Petnames on Wikipedia https://en.wikipedia.org/wiki/Petname
- Petnames paper by Spritely https://spritelyproject.org/news/petname-systems.html
- Petnames paper by Christine Lemmer-Webber https://github.com/cwebber/rebooting-the-web-of-trust-spring2018/blob/petnames/draft-documents/petnames.md
- Ink and Switch Backchannel https://www.inkandswitch.com/backchannel/
- Overview: http://www.skyhunter.com/marcs/petnames/IntroPetNames.html
- Paper on Petname UX: Sadek Ferdous; Audun Jøsang; Kuldeep Singh; Ravishankar Borgaonkar (2009). Security Usability of Petname Systems. in [Identity and Privacy in the Internet Age 14th Nordic Conference on Secure IT Systems, NordSec 2009, Oslo, Norway, 14-16 October 2009, Proceedings](https://link.springer.com/book/10.1007/978-3-642-04766-4). [Google Books](https://books.google.com/books?id=mSMsqoqufMoC&pg=PP1#v=onepage&q&f=false).
- [GNU Name System](https://en.wikipedia.org/wiki/GNUnet#GNU_Name_System) is a petname system

**Comment by bfollington** [comment]
Some early thinking & sketching from my end.

From a user-first perspective I see trust working something like this:

<img width="664" alt="Trust layers@2x" src="https://github.com/subconsciousnetwork/subconscious/assets/5009316/3a89d802-9a5b-42a8-8d45-f519e6d5617c">

If there were only **one** thing users care about its whether they can feel **safe** around another user, and this is determined by the threshold shown above. Not all users will have the same threshold but I placed it where I believe it commonly lies.

---

Following this logic, I sketched some ideas about how to present names to surface & present the information that users need to make this assessment of "assumed trust".

<img width="954" alt="Ideation@2x" src="https://github.com/subconsciousnetwork/subconscious/assets/5009316/fecb073f-7a9b-4b72-9376-3052a37b05da">

A, B and C are all alternative ideas for a long-press view of a user's name.

(source: https://www.figma.com/file/moadOLU5Nk2w1hDd4BAooH/Petnames-%26-Trust?type=design&node-id=0%3A1&t=q50elV7Sz9GW3N06-1 )

**Comment by gordonbrander** [comment]
I like this a lot. Surfacing "mutuality" seems like a very important signal.

Another visual signal we might use is "PFP rows" in places like post footers or profile headers.

![link_pfps](https://github.com/subconsciousnetwork/subconscious/assets/58421/f90e55b0-c1d3-4b8d-978d-8e16b7a0f68c)

**Comment by bfollington** [comment]
Similarly, if many of the users you follow have blocked/muted another user you almost certainly don't want to follow them. This could be signalled in the UI with a different icon etc.
