### ISSUE TITLE
Disallow "." in petnames

### ISSUE THREAD

**Issue by jsantell** [subconsciousnetwork/subconscious#629]
Related to #619, `"."` is allowed when adding a new petname, leading to ambiguities when referencing later

**Comment by bfollington** [comment]
Some added context: we want petnames to support `"."` if (and only if) it is peer-path of a Slashlink. @gordonbrander has sketched the idea of `Petname` being composed of several `Petname.Part`s each of which _cannot_ contain a `"."` but will be rendered as a joined string in the UI.
