### ISSUE TITLE
Persist gateway provisioning ID when kicking off deployment

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#643]
During provisioning, the gateway ID can be used to check the status of a gateway. Right now it's stored in memory and used by `GatewayProvisioningService.waitForGatewayProvisioning`, which works great _if_ the process succeeds.

However, if the user were to quit out of the app or the gateway takes longer than expected to provision we will throw away the gateway ID and be unable to check on it again later. 

Instead, we should persist the gateway ID and allow the app to re-check provisioning status after a timeout, crash or relaunch. This should be shown & be clearable in the `GatewaySettings` view where the provisioning status widget is located. 

# Questions

- Where do we store this? AppDefaults? Memo? SQLite metadata table?

**Comment by bfollington** [comment]
From @gordonbrander:
> AppDefaults is probably a good place

**Comment by gordonbrander** [comment]
@bfollington we may want to persist the invite code to AppDefaults as well, so we can re-submit invite code, at the point that cloudctl supports re-submitting invite code.
