### ISSUE TITLE
As a user, I want to be able to merge related notes, so I can create atomic notes.

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#66]
## Story

As a user, I want to be able to merge related notes, so I can create atomic notes.

## Description

(See designs)

Allow renaming slug through search-or-create style flow that enables users to merge note with other notes when the slug is the same.

- Rename flow is done through typeahead search
- Suggestions
  - De-duplicated names (append incrementing number) (rename)
  - Slugs for links to pages that don't exist yet (rename)
  - Searches that don't have corresponding entries (rename)
  - Merge notes (merge)

On choosing merge, current note contents are appended to chosen note.

**Comment by bmorphism** [comment]
Are these like the Markov kernels of active inference or more static?
