### ISSUE TITLE
Search shows own profile

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#667]
<img src="https://github.com/subconsciousnetwork/subconscious/assets/58421/8800b989-3b2f-4730-bf2f-84dbddbf6810" width="320">

<img src="https://github.com/subconsciousnetwork/subconscious/assets/58421/11d96e6a-4438-4192-ac3b-10d5948dbec5" width="320">

**Comment by bfollington** [comment]
Related to https://github.com/subconsciousnetwork/subconscious/issues/593

We need to filter out any hidden slugs from the DB results.

**Comment by bfollington** [comment]
Resolved in https://github.com/subconsciousnetwork/subconscious/pull/627
