### ISSUE TITLE
Button to retry resolving peer

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#684]
> As a user, I want to be able to retry following after a failure, so I can recover from an error condition caused by bugs, service outages, or loss of connectivity.

Ran into this while trying to resolve some dids. The dids are/were valid, but once you get a failure, there's no obvious way to retry. We could add a button to retry for profiles that fail to resolve.

<img src="https://github.com/subconsciousnetwork/subconscious/assets/58421/d0daea07-8c4c-44f9-944b-3a5b013229bd" width="400">

**Comment by bfollington** [comment]
The gateway will continue trying to resolve these in the background, so retrying resolution is effectively the same as syncing with the gateway. This means we can offer the affordance to retry as an alternative way to sync and refresh. 

Should the retry button trigger a background waiting process again, or just check once?
