### ISSUE TITLE
Loading indicator transposed outside of the header bar

### ISSUE THREAD

**Issue by jsantell** [subconsciousnetwork/subconscious#709]
Occasionally when loading a sphere, the loading indicator appears (the border-stripe moving around the header bar) and is transposed such that it no longer aligns with the header bar

**Comment by bfollington** [comment]
This seems, to me, like a race condition on the layout engine. It's trying to animate a zero-sized container or something like that.

Suggestion from @gordonbrander is to explore a fixed height wrapping container.
