### ISSUE TITLE
After migration my notes the notebook view was empty, but my notes were present on my profile

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#723]
Per the title, after migrating my notes with #627 my notebook view was empty, but my notes were visible on my profile.
After creating a new note the notes rendered in the main list, but the count was still out of date until I pulled-to-refresh.

I suspect if I had just refreshed initially it would also have fixed the view, we must not be refreshing at the completion of indexing.

**Comment by gordonbrander** [comment]
Tested migration from 0.0.7 by installing 0.0.7, then flashing with `main`.

Findings: local notes were migrated correctly.

**Comment by gordonbrander** [comment]
Wild guess without any info: these were sphere notes, and when #627 was flashed, Noosphere was off. Thus, the gateway sync was not kicked off, and after it, the sphere sync was not kicked off. Since there were no local drafts, the app showed an empty state.

@bfollington does this sound plausible?

**Comment by bfollington** [comment]
@gordonbrander yep that definitely sounds plausible, I'm not sure WHY the Noosphere setting turned off but I recall  having to turn it back on post-migration.

I have a faint memory of seeing the issue again later in testing but I can't recall if Noosphere was off the second time.

**Comment by bfollington** [comment]
Possible duplicate of https://github.com/subconsciousnetwork/subconscious/issues/659
