### ISSUE TITLE
Re-using invite code fails silently during FRE

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#738]
Re-using invite code fails silently, without informing the user that the invite code is invalid or already used.

We do generate a `2023-06-20 14:48:00.213597-0400 Subconscious[3839:972420] [app] [action] failProvisionGateway("Failed to provision gateway: HTTP 500: Invite code is invalid or already used")` but log and swallow the error in the FRE.

We should consider displaying some sort of feedback in the FRE if possible.

**Comment by cdata** [comment]
Just for reference, @jsantell is working on https://github.com/subconsciousnetwork/subconscious-cloud/issues/6 which should help improve some of the UX from the other direction.

**Comment by gordonbrander** [comment]
Is this closed now @bfollington?
