### ISSUE TITLE
All notes show the title as their excerpt by default

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#793]
Our intention is to show previews of each note in the feed / transclusions so you can get a glimpse of content without clicking through. Currently, every preview will look like this by default:

<img width="375" alt="image" src="https://github.com/subconsciousnetwork/subconscious/assets/5009316/4a1e9827-0938-49da-b996-fd3db8781a12">

When creating a note we autopopulate the first line with the title, which is fine as a pattern. The problem is that the title automatically becomes the first block and is the entirety of the excerpt as a result. To get the intended outcome I find myself making notes, writing them and then deleting the title afterwards.

<img width="428" alt="image" src="https://github.com/subconsciousnetwork/subconscious/assets/5009316/35193da2-726a-4a97-9f66-0b30c1652d37">

I can see two fixes here:
1. Change the UX for naming a note to set the note title _without_ putting it in the body
2. Skip over the first block when picking the excerpt if (and only if) it matches the title

**Comment by gordonbrander** [comment]
We should include the first 2 blocks in the excerpt (I thought we had made this change already 🤔)

**Comment by bfollington** [comment]
I recall fixing the excerpt logic but not considering two blocks. Did a quick hack to test the first two block behaviour, it's better but it does still "double up" the title 

<img width="364" alt="image" src="https://github.com/subconsciousnetwork/subconscious/assets/5009316/5eea7e74-350c-4b5c-af6a-b8588efbd3db">

**Comment by gordonbrander** [comment]
That looks right to me. IMO the slug does not suffice as a title. 

We could also consider making the first block medium weight font. I believe the Figma mocks take this approach.
