### ISSUE TITLE
Cannot add new user from scanning QR code

### ISSUE THREAD

**Issue by jsantell** [subconsciousnetwork/subconscious#824]
After scanning a QR code to follow a user, I click "Done", but nothing happens -- ~~I need to add a nickname before continuing, but no validation appears (until focusing the nickname test field)~~ even adding a nickname does not satiate the ability to hit "Done" on this screen -- the QR code's did key does populate

Turns out it was the newline in the DID from the QR

**Comment by bfollington** [comment]
Actions:

- Trim whitespace from the inserted value
- Ensure form validation is updated when populated by QR code

Related https://github.com/subconsciousnetwork/subconscious/issues/826

**Comment by bfollington** [comment]
Closed by https://github.com/subconsciousnetwork/subconscious/pull/967
