### ISSUE TITLE
Investigate whether running tests can trigger `Foreign Error: Read corrupted data at file offset None backtrace ()`

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#838]
So, this issue has been around for a while. My latest hunch is that it's related to the simulator, specifically teardown when running unit tests. (See https://github.com/subconsciousnetwork/subconscious/issues/693)

Running _a single test case_ will start the app in the simulator in the background (printing logs showing sphere initialization) and then kill the app as soon as the test finishes. I don't see a deinit log message for Noosphere or any spheres in the output, seems like it kills the process forcefully?

This strikes me as asking for trouble... it's not always going to be a problem but it could be... which would explain the intermittent nature of the issue.

## Actions

- Try to trigger the corruption issue by running tests
- Interact with the app in the background while tests are running
- Write a test that spams sphere mutating operations and unexpectedly kills noosphere
- Create a situation where the app is "doing noosphere work" in the background and is killed unexpectedly when tests end

**Comment by bfollington** [comment]
RE: why does the simulator have to run in the first place?

> The simulator is actually an emulator.  The tests run in the emulated device environment.

**Comment by cdata** [comment]
Some errata about the meaningful differences between the simulator and real devices: https://help.apple.com/simulator/mac/current/#/devb0244142d
