### ISSUE TITLE
Integrate Recovery FFI

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#889]
Implement UI to call the Recovery FFI https://github.com/subconsciousnetwork/noosphere/issues/337 

Delete broken app install, add gateway URL and download.

**Comment by gordonbrander** [comment]
We'll want to include recovery UI.

Preferably, we can infer broken state and kick off a recovery flow.

We will need from user:

- Mnemonic

We should have: 

- Gateway URL
- Sphere DID

If we have gateway URL and Sphere DID, but can't open Noosphere DB, then pop recovery UI.
