### ISSUE TITLE
Build errors on main

### ISSUE THREAD

**Issue by jsantell** [subconsciousnetwork/subconscious#890]
Getting the following errors:
<img width="475" alt="Screenshot 2023-09-11 at 1 12 21 PM" src="https://github.com/subconsciousnetwork/subconscious/assets/641267/527a910a-8ce6-4b9b-8c49-d771161baae9">
<img width="465" alt="Screenshot 2023-09-11 at 1 17 26 PM" src="https://github.com/subconsciousnetwork/subconscious/assets/641267/3080faab-d179-4627-9b4e-71f8b53d51b3">

**Comment by bfollington** [comment]
I'm suspicious that this is the result of some kind of package resolution / installation issue. We recently upgraded the version of ObservableStore that we depend on (#884). Does this same issue occur when based on a commit prior to that PR merging?
