### ISSUE TITLE
Failed recovery on device with v0.0.11+1

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#920]
After flashing device with Subconscious@v0.0.11 and attempting to recover gateway, I experienced the following error.

- The first error happened after hitting submit the first time.
- The second error happened after hitting submit again.
- After this, I get either error upon hitting submit repeatedly.

![03BC3410-D66B-4D62-9671-2A2EC9185A72](https://github.com/subconsciousnetwork/subconscious/assets/58421/6873bfbe-b766-4013-99eb-4ebd809f2c4f)

![IMG_0899](https://github.com/subconsciousnetwork/subconscious/assets/58421/49102b9d-8864-4fa2-a8c0-4c9372194bd7)

**Comment by bfollington** [comment]
Due to effectively DDoSing the gateway, new versions of Noosphere resolved this.
