### ISSUE TITLE
Notes created in one tab don't notify other tabs to refresh

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#937]
We should be kicking up a notification to AppStore.

Steps to repro:

- Open the feed
- Search or create
- Create a note
- Switch to notebook tab

Result: no new note in list. You must pull to refresh to see note. 

Expected: note should already be present in other lists.

**Comment by bfollington** [comment]
@gordonbrander additional info from my testing:

- the Feed _does_ update for me if I create a note from the Notebook or Profile
- the Notebook _never_ updates if I create a note from the Feed or Profile
- the Profile updates the next time that indexing finishes if I create a note from the Feed or Notebook
