### ISSUE TITLE
Profile does not show that you follow after following

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#946]
Steps to reproduce:

- Go to profile you don't follow
- Tap follow (follow sheet opens)
- Confirm follow (Follow sheet retracts after delay. See related issue #945)

What happens: profile still says "Follow" as if you did not follow it. If you refresh, the correct follow status will be reflected.

What should happen: profile following status should be refreshed as soon as follow sheet retracts.

**Comment by bfollington** [comment]
Could be related to https://github.com/subconsciousnetwork/subconscious/issues/938

**Comment by bfollington** [comment]
FWIW I've seen this work in the last day, so this may be intermittent / latency / racing?
